version: '3.0'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: database
    expose:
      - 5432
    networks:
      - challenge_network
  backend:
    build:
      dockerfile: ./backend/Dockerfile
      context: .
    image: ghcr.io/haxagoncz/undefined-behavior-backend:latest
    depends_on:
     - postgres
    networks:
      - challenge_network
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./docker/flags:/var/flags:ro
    environment:
      RUST_LOG: debug
      HAXAGON_DATABASE_URL: postgres://postgres:postgres@postgres/database
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
      context: .
    image: ghcr.io/haxagoncz/undefined-behavior-frontend:latest
    ports:
      - 80:80
    networks:
      - challenge_network
    depends_on:
      - postgres
      - backend

networks:
  challenge_network:
    driver: bridge