version: '3.0'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: database
    expose:
      - 5432
    networks:
      - challenge_network
  backend:
    build: ./
    image: ghcr.io/haxagoncz/undefined-behavior-backend:latest
    networks:
      - challenge_network
    expose:
      - 3000
    environment:
      HAXAGON_DATABASE: postgres://postgres:postgres@postgres/database

networks:
  challenge_network:
    driver: bridge